# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shutit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField()),
                ('boarding_time', models.DateTimeField(blank=True)),
                ('is_waiting', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Queues',
                'verbose_name': 'Queue',
            },
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id_number',
            field=models.TextField(max_length=65, unique=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='passanger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shutit.Passenger'),
        ),
    ]
